data:
  data_path: '//pscratch/sd/m/mcraigie/cosmogrid/'          # path to main data directory
  data_subpath: 'unmasked'                                   # file name or folder (e.g. 'patches')
  data_type: 'patches'                                      # patches or precalc
  datahandler_kwargs:
    load_subset: 2500                                       # Subset of cosmologies to load (saves memory), 2500 for all
    patch_subset: 16                                    # Subset of patches per cosmology, 192 for all
    val_ratio: 0.2                                          # Portion of data to use for validation
    test_ratio: 0.2                                         # Portion of data to use for testing
    seed: 0                                                 # Random seed for data splitting
    pre_average: False

regressor:
  regressor_kwargs:
    regressor_type: 'patch'
    model_type: 'ost'                                       # Type of model to use: 'mst', 'ost', 'ps', 'resnet'
    model_kwargs:
      reduction: 'rot_avg'
      ost_type: 'subnet'
      init_morlet: True
    regressor_inputs: 11                                    # Number of features
    regressor_hiddens: [128, 128]
    regressor_batchnorm: False

training:
  num_epochs: [100000, 100000]                                          # Number of training epochs
  batch_size: 128                                           # Batch size
  learning_rate: [0.001, 0.001,]                                     # Learning rate

analysis:
  analysis_name: 'ost_oms8_newcriterion'
  data_subsets: [30, 125,]   # Subsets of the data for the scaling analysis
  repeats: 1