load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches/patches/'                 # the folder to load from
#load_path: '//pscratch/sd/m/mcraigie/dirac/patches/masked/'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/precalc/'
file_name:  'mst_full'

method: 'mst'
kwargs:
  size: 128
  num_scales: 4
  num_angles: 4
  reduction: 'none'
  device: 'cuda:0'
