load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches/patches/'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/precalc'
file_name:  'mst_masked'

method: 'mst'
kwargs:
  size: 128
  num_scales: 4
  num_angles: 4
  reduction: 'rot_avg'
  device: 'cuda:0'
