load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches/patches_log_std'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/precalc'                         # must specify the .npy file for output
file_name: 'ost_rot'

method: 'ost'
kwargs:
  filter_path: '//global/homes/m/mcraigie/ost_project/OptimisedFiltersLensing/outputs/datascaling/patches/ost/ost_rot_16//subset_125/filters.pt'
  reduction: 'rot_avg'
  device: 'cuda:0'
