load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches_log_std'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/'         # must specify the .npy file for output
file_name: 'ost_precalc_rot_avg'

method: 'ost'
kwargs:
  filter_path: '//global/homes/m/mcraigie/ost_project/OptimisedFiltersLensing/outputs/datascaling/ost/rot_avg/subset_2000/filters.pt'
  reduction: 'rot_avg'
  device: 'cuda:0'
