load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/ps_precalc.npy'         # must specify the .npy file for output

method: 'ps'
kwargs:
  size: 128
  num_bins: 22
  device: 'cuda:0'


