load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches_log_std'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/'
save_name: 'ps_precalc'

method: 'ps'
kwargs:
  size: 128
  num_bins: 12
  device: 'cuda:0'


