data:
  data_path: '//pscratch/sd/m/mcraigie/cosmogrid/'          # path to main data directory
  data_subpath: 'ost_precalc_std.npy'                       # file name or folder (e.g. 'patches')
  is_patches: False                                         # True if the data is a set of patches
  load_subset: 2500                                         # Subset of cosmologies to load (saves memory), 2500 for all
  sub_batch_subset: 16                                      # Subset of patches per cosmology, 192 for all
  val_ratio: 0.2                                            # Portion of data to use for validation
  test_ratio: 0.2                                           # Portion of data to use for testing

regressor:
  regressor_type: 'precalc'                                 # patch or precalc
  regressor_kwargs:
    model_type: 'ost'                                       # Type of model to use: 'mst', 'ost', 'ps', 'resnet'
    model_kwargs:
      input_size: 11
    regressor_hiddens: null

training:
  num_epochs: 1000                                          # Number of training epochs
  batch_size: 128                                           # Batch size
  learning_rate: 0.001                                      # Learning rate

analysis:
  data_subsets: [25, 50, 100, 250, 500, 1000, 1500, 2000]   # Subsets of the data for the scaling analysis
  repeats: 10