data:
  data_path: '//pscratch/sd/m/mcraigie/cosmogrid/'          # path to main data directory
  data_subpath: 'ost_rot_std.npy'                       # file name or folder (e.g. 'patches')
  data_type: 'precalc'                                      # patches or precalc
  datahandler_kwargs:
    load_subset: 2500                                       # Subset of cosmologies to load (saves memory), 2500 for all
    sub_batch_subset: 16                                    # Subset of patches per cosmology, 192 for all
    val_ratio: 0.2                                          # Portion of data to use for validation
    test_ratio: 0.2                                         # Portion of data to use for testing
    seed: 0                                                 # Random seed for data splitting
    pre_average: True                                       # generally, we want this true for precalc/false otherwise

regressor:
  regressor_kwargs:
    regressor_type: 'precalc'
    model_type: 'ost'                                       # Type of model to use: 'mst', 'ost', 'ps', 'resnet'
    model_kwargs: null
    regressor_inputs: 11                                    # Number of features
    regressor_hiddens: null

training:
  num_epochs: 500                                          # Number of training epochs
  batch_size: 128                                           # Batch size
  learning_rate: 0.01                                     # Learning rate

analysis:
  analysis_name: 'ost_rot_16'
  data_subsets: [30, 60, 125, 250, 500] #, 1000, 2000]   # Subsets of the data for the scaling analysis
  repeats: 10