load_path: '//pscratch/sd/m/mcraigie/cosmogrid/patches'                 # the folder to load from
save_path: '//pscratch/sd/m/mcraigie/cosmogrid/mst_precalc.npy'         # must specify the .npy file for output
method: 'mst'
kwargs:
  size: 128
  num_scales: 6
  num_angles: 6

